name: CI for Gmail AI Search

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check Docker installation
      run: docker --version

    - name: Check Docker Compose installation
      run: docker-compose --version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and run Docker Compose
      run: docker-compose up --build --exit-code-from app